coverage:
  ignore:  # files and folders that will be removed during processing
    - "blast/static/blast/scripts/codemirror.js"
    - "blast/static/blast/scripts/active-line.js"
    - "blast/static/blast/scripts/searchcursor.js"
    - "blast/static/blast/scripts/kendo*"
    - "blast/static/blast/scripts/scribl.1.1.5-hotdogee.js"
    - "blast/static/blast/scripts/dragscrollable.js"
    - "blast/static/blast/scripts/dataTables.scroller.js"
    - "clustal/static/clustal/scripts/jquery*"
    - "hmmer/static/hmmer/scripts/jquery*"

