coverage:
  ignore:  # files and folders that will be removed during processing
    - "app/static/app/scripts/bootstrap.js"
    - "app/static/app/scripts/jquery.js"
    - "app/static/app/scripts/respond.src.js"
    - "app/static/app/scripts/underscore.js"
    - "app/static/app/scripts/jquery.validate.js"
    - "app/static/app/scripts/marked.min.js"
    - "app/static/app/css/bootstrap.css"

    - "blast/static/blast/scripts/active-line.js"
    - "blast/static/blast/scripts/codemirror.js"
    - "blast/static/blast/scripts/d3.js"
    - "blast/static/blast/scripts/searchcursor.js"
    - "blast/static/blast/scripts/backbone.js"
    - "blast/static/blast/scripts/bootstrap-switch.js"
    - "blast/static/blast/scripts/chroma.js"
    - "blast/static/blast/scripts/dataTables.bootstrap.js"
    - "blast/static/blast/scripts/dataTables.colReorder.js"
    - "blast/static/blast/scripts/dataTables.tableTools.js"
    - "blast/static/blast/scripts/dragscrollable.js"
    - "blast/static/blast/scripts/jquery-ui.js"
    - "blast/static/blast/scripts/jquery.hoverIntent.js"
    - "blast/static/blast/scripts/jquery.validate.js"
    - "blast/static/blast/css/bootstrap-select.css"
    - "blast/static/blast/css/bootstrap-switch.css"
    - "blast/static/blast/css/colReorder.dataTables.css"
    - "blast/static/blast/css/dataTables.bootstrap.css"
    - "blast/static/blast/css/jquery.dataTables.css"

    - "hmmer/static/hmmer/scripts/jquery.hoverIntent.js"
    - "hmmer/static/hmmer/scripts/jquery.validate.js"

    - "clustal/static/clustal/scripts/jquery.hoverIntent.js"
    - "clustal/static/clustal/scripts/jquery.validate.js"
