exclude_patterns:
- "blast/static/blast/css/codemirror.css"
- "blast/static/blast/css/xq-light.css"
- "blast/static/blast/css/kendo.common-bootstrap.core.css"
- "blast/static/blast/css/kendo.bootstrap.css"
- "blast/static/blast/scripts/codemirror.js"
- "blast/static/blast/scripts/active-line.js"
- "blast/static/blast/scripts/searchcursor.js"
- "blast/static/blast/scripts/dataTables.scroller.js"
- "blast/static/blast/scripts/scribl.1.1.5-hotdogee.js"
- "blast/static/blast/scripts/bootstrap-select-hotdogee.js"
- "blast/static/blast/scripts/dragscrollable.js"
