exclude_paths:
- "blast/staic/blast/css/codemirror.css"
- "blast/staic/blast/css/xq-light.css"
- "blast/staic/blast/css/kendo.common-bootstrap.core.css"
- "blast/staic/blast/css/kendo.bootstrap.css"
- "blast/staic/blast/css/jquery-ui.css"
- "blast/staic/blast/dataTables/css/jquery.dataTables.css"
- "blast/staic/blast/dataTables/css/dataTables.scroller.css"
- "blast/staic/blast/dataTables/css/dataTables.colReorder.css"
- "blast/staic/blast/dataTables/css/dataTables.bootstrap.css"
- "blast/staic/blast/css/bootstrap-select.css"
- "blast/staic/blast/css/bootstrap-switch.css"
- "app/static/app/scripts/jquery-1.11.1.js"
- "app/static/app/scripts/bootstrap.js"
- "app/static/app/scripts/respond.src.js"
- "blast/static/blast/scripts/chroma.js"
- "blast/static/blast/scripts/codemirror-compressed.js"
- "blast/static/blast/scripts/kendo-hotdogee.js"
- "blast/static/blast/scripts/jquery-ui.js"
- "blast/static/blast/scripts/dragscrollable.js"
- "blast/static/blast/dataTables/js/jquery.dataTables-hotdogee.js"
- "blast/static/blast/dataTables/js/dataTables.scroller.js"
- "blast/static/blast/dataTables/js/dataTables.colReorder.js"
- "blast/static/blast/dataTables/js/dataTables.tableTools.js"
- "blast/static/blast/dataTables/js/dataTables.bootstrap.js"
- "blast/static/blast/scripts/underscore.js"
- "blast/static/blast/scripts/backbone.js"
- "blast/static/blast/scripts/scribl.1.1.5-hotdogee.js"
- "blast/static/blast/scripts/bootstrap-select-hotdogee.js"
- "blast/static/blast/scripts/bootstrap-switch.js"
- "blast/static/blast/scripts/underscore.js"
- "blast/static/blast/scripts/jquery.hoverIntent.js"
- "blast/static/blast/scripts/jquery.validate.js"
- "clustal/static/clustal/scripts/underscore.js"
- "clustal/static/clustal/scripts/jquery.hoverIntent.js"
- "clustal/static/clustal/scripts/jquery.validate.js"
- "hmmer/static/hmmer/scripts/underscore.js"
- "hmmer/static/hmmer/scripts/jquery.hoverIntent.js"
- "hmmer/static/hmmer/scripts/jquery.validate.js"
- "blast/static/blast/scripts/codemirror/*"
