exclude_paths:
- "blast/staic/blast/css/codemirror.css"
- "blast/staic/blast/css/xq-light.css"
- "blast/staic/blast/css/kendo.common-bootstrap.core.css"
- "blast/staic/blast/css/kendo.bootstrap.css"
- "blast/static/blast/scripts/kendo-hotdogee.js"
- "blast/static/blast/scripts/dragscrollable.js"
- "blast/static/blast/scripts/scribl.1.1.5-hotdogee.js"
- "blast/static/blast/scripts/bootstrap-select-hotdogee.js"
- "clustal/static/clustal/scripts/jquery.hoverIntent.js"
- "clustal/static/clustal/scripts/jquery.validate.js"
- "hmmer/static/hmmer/scripts/jquery.hoverIntent.js"
- "hmmer/static/hmmer/scripts/jquery.validate.js"
- blast/static/blast/scripts/codemirror.js
- blast/static/blast/scripts/active-line.js
- blast/static/blast/scripts/searchcursor.js
