version: '3'
services:
    postgres:      
      container_name: 'postgres'
      image: postgres:alpine
      environment: 
        POSTGRES_PASSWORD: django1234
      ports:  
        - "5432:5432"
    
    workspace:
      build: .
      links: 
        - postgres
        - postgres:postgresql
        - rabbitmq
        - memcache
      restart: always
      ports: 
        - "8000:8000"
      depends_on:
        - postgres
        - rabbitmq
        - memcache
    
    memcache: 
      image: memcached:1.5.1-alpine
      ports:
        - "11211:11211"
    rabbitmq:
      image: rabbitmq:3.6.12-management-alpine  
      ports:
        - "4369:4369"
      
volumes:
  pgdata:
            

