# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hmmer', '0002_auto_20180104_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmmerdb',
            name='fasta_file',
            field=filebrowser.fields.FileBrowseField(default='', max_length=100, verbose_name='FASTA file path'),
        ),
        migrations.AlterField(
            model_name='hmmerdb',
            name='is_shown',
            field=models.BooleanField(default=None, help_text='Display this database in the HMMER submit form'),
        ),
        migrations.AlterField(
            model_name='hmmerdb',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hmmerqueryrecord',
            name='result_status',
            field=models.CharField(default='WAITING', max_length=32),
        ),
    ]
