from django.shortcuts import render
import json

def test_main(request):
    blastdb_list = [['Genome Assembly', 'Nucleotide', 'Agla_Btl03082013.genome_new_ids.fa', 'Anoplophora glabripennis', ''],
    ['Genome Assembly', 'Nucleotide', 'Aros01112013-genome_new_ids.fa', 'Athalia rosae', ''],
    ['Genome Assembly', 'Nucleotide', 'Ccap01172013-genome_new_ids.fa', 'Ceratitis capitata', ''],
    ['Genome Assembly', 'Nucleotide', 'Clec_Bbug02212013.genome_new_ids.fa', 'Cimex lectularius', ''],
    ['Genome Assembly', 'Nucleotide', 'diaci1.1_new_ids.fa', 'Diaphorina citri', ''],
    ['Genome Assembly', 'Nucleotide', 'Edan07162013.scaffolds_new_ids.fa', 'Ephemera danica', ''],
    ['Genome Assembly', 'Nucleotide', 'Eaff_11172013.genome_new_ids.fa', 'Eurytemora affinis', ''],
    ['Genome Assembly', 'Nucleotide', 'Focc_FINAL.scaffolds_new_ids.fa', 'Frankliniella occidentalis', ''],
    ['Genome Assembly', 'Nucleotide', 'Lful_Scha04012013-genome_new_ids.fa', 'Ladona fulva', ''],
    ['Genome Assembly', 'Nucleotide', 'Ldec.genome.10062013_new_ids.fa', 'Leptinotarsa decemlineata', ''],
    ['Genome Assembly', 'Nucleotide', 'Ofas.scaffolds_new_ids.fa', 'Oncopeltus fasciatus', ''],
    ['Genome Assembly', 'Nucleotide', 'Oabi11242013.genome_new_ids.fa', 'Orussus abietinus', ''],
    ['Genome Assembly', 'Nucleotide', 'Pven10162013.scaffolds_new_ids.fa', 'Pachypsylla venusta', ''],
    ['Genome Assembly', 'Nucleotide', 'Ptep01282013.genome_new_ids.fa', 'Parasteatoda tepidariorum', ''],
    ['Genome Assembly', 'Nucleotide', 'Tpre_FINAL.scaffolds_new_ids.fa', 'Trichogramma pretiosum', ''],
    ['Transcript', 'Nucleotide', 'AGLA_new_ids.fna', 'Anoplophora glabripennis', ''],
    ['Transcript', 'Nucleotide', 'AROS_new_ids.fna', 'Athalia rosae', ''],
    ['Transcript', 'Nucleotide', 'CCAP_new_ids.fna', 'Ceratitis capitata', ''],
    ['Transcript', 'Nucleotide', 'CLEC_new_ids.fna', 'Cimex lectularius', ''],
    ['Transcript', 'Nucleotide', 'maker_genes_diaci1.1_transcripts_NALmod_new_ids.fasta', 'Diaphorina citri', ''],
    ['Transcript', 'Nucleotide', 'EDAN_new_ids.fna', 'Ephemera danica'], ['Transcript', 'Nucleotide', 'EAFF_new_ids.fna', 'Eurytemora affinis', ''],
    ['Transcript', 'Nucleotide', 'FOCC_new_ids.fna', 'Frankliniella occidentalis', ''],
    ['Transcript', 'Nucleotide', 'LFUL_new_ids.fna', 'Ladona fulva', ''],
    ['Transcript', 'Nucleotide', 'LDEC_new_ids.fna', 'Leptinotarsa decemlineata', ''],
    ['Transcript', 'Nucleotide', 'OFAS_new_ids.fna', 'Oncopeltus fasciatus', ''],
    ['Transcript', 'Nucleotide', 'OABI_new_ids.fna', 'Orussus abietinus', ''],
    ['Transcript', 'Nucleotide', 'PVEN_new_ids.fna', 'Pachypsylla venusta', ''],
    ['Transcript', 'Nucleotide', 'PTEP_new_ids.fna', 'Parasteatoda tepidariorum', ''],
    ['Transcript', 'Nucleotide', 'TPRE_new_ids.fna', 'Trichogramma pretiosum', ''],
    ['Protein', 'Peptide', 'AGLA_new_ids.faa', 'Anoplophora glabripennis', ''],
    ['Protein', 'Peptide', 'AROS_new_ids.faa', 'Athalia rosae', ''],
    ['Protein', 'Peptide', 'CCAP_new_ids.faa', 'Ceratitis capitata', ''],
    ['Protein', 'Peptide', 'CLEC_new_ids.faa', 'Cimex lectularius', ''],
    ['Protein', 'Peptide', 'maker_genes_diaci1.1_proteins_NALmod_new_ids.fasta', 'Diaphorina citri', ''],
    ['Protein', 'Peptide', 'EDAN_new_ids.faa', 'Ephemera danica', ''],
    ['Protein', 'Peptide', 'EAFF_new_ids.faa', 'Eurytemora affinis', ''],
    ['Protein', 'Peptide', 'FOCC_new_ids.faa', 'Frankliniella occidentalis', ''],
    ['Protein', 'Peptide', 'LFUL_new_ids.faa', 'Ladona fulva', ''],
    ['Protein', 'Peptide', 'LDEC_new_ids.faa', 'Leptinotarsa decemlineata', ''],
    ['Protein', 'Peptide', 'OFAS_new_ids.faa', 'Oncopeltus fasciatus', ''],
    ['Protein', 'Peptide', 'OABI_new_ids.faa', 'Orussus abietinus', ''],
    ['Protein', 'Peptide', 'PVEN_new_ids.faa', 'Pachypsylla venusta', ''],
    ['Protein', 'Peptide', 'PTEP_new_ids.faa', 'Parasteatoda tepidariorum', ''],
    ['Protein', 'Peptide', 'TPRE_new_ids.faa', 'Trichogramma pretiosum', '']]
    blastdb_type_counts = {'genome_assembly': 15, 'protein': 15, 'transcript': 15}
    return render(request, 'blast/main.html', {
        'title': 'BLAST Query',
        'blastdb_list': json.dumps(blastdb_list),
        'blastdb_type_counts': blastdb_type_counts,
        'iframe': False
    })
