# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0007_auto_20180104_1513'),
        ('blast', '0007_auto_20180104_1450'),
    ]

    operations = [
    ]
