# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-16 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0007_auto_20180104_1450'),
        ('hmmer', '0001_initial'),
        ('hmmer', '0002_auto_20180104_1450')
    ]

    operations = [
        migrations.DeleteModel(
            name='Organism',
        ),
    ]
