# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0008_delete_organism'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blastdb',
            options={'verbose_name': 'BLAST database'},
        ),
        migrations.AlterModelOptions(
            name='blastqueryrecord',
            options={'verbose_name': 'BLAST result'},
        ),
        migrations.AlterField(
            model_name='blastdb',
            name='is_shown',
            field=models.BooleanField(default=None, help_text='Display this database in the BLAST submit form'),
        ),
        migrations.AlterField(
            model_name='blastdb',
            name='title',
            field=models.CharField(help_text='This is passed into makeblast -title', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blastqueryrecord',
            name='result_status',
            field=models.CharField(default='WAITING', max_length=32),
        ),
        migrations.AlterField(
            model_name='jbrowsesetting',
            name='blast_db',
            field=models.OneToOneField(help_text='The BLAST database used as the reference in Jbrowse', on_delete=django.db.models.deletion.CASCADE, to='blast.BlastDb', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='jbrowsesetting',
            name='url',
            field=models.URLField(help_text='The URL to Jbrowse using this reference', unique=True, verbose_name='Jbrowse URL'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='blast_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast.BlastDb', verbose_name='BLAST DB'),
        ),
    ]
