# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0008_delete_organism'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO public.blast_sequencetype (id, molecule_type, dataset_type) VALUES (1, 'nucl', 'Genome Assembly');"
        ),
        migrations.RunSQL(
            "INSERT INTO public.blast_sequencetype (id, molecule_type, dataset_type) VALUES (2, 'nucl', 'Transcript');"
        ),
        migrations.RunSQL(
            "INSERT INTO public.blast_sequencetype (id, molecule_type, dataset_type) VALUES (4, 'prot', 'Protein');"
        )
    ]
