; supervisor config file

[unix_http_server]
file=run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)


[supervisord]
nodaemon = true
logfile=logs/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=logs/            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://APP_HOME/run/supervisor.sock ; use a unix:// URL  for a unix socket

[program:production]
autostart = true
directory=APP_HOME/production
;command = PRODUCTION/start_app.sh PRODUCTION
command = APP_HOME/.venv/bin/startapp.sh
priority = 1

[program:training]
autostart = true
directory=APP_HOME/training
;command = TRAINING/start_app.sh TRAINING
command = APP_HOME/.venv/bin/startapp.sh
priority = 2

[program:nginx]
autostart = true
command = nginx -g 'daemon off;'
priority = 3